apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-peer-auth
  namespace: test
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: mode-disabled
  namespace: test
spec:
  mtls:
    mode: DISABLE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: permissive-peer-auth
  namespace: test
spec:
  mtls:
    mode: PERMISSIVE